services:
  postgres:
    image: postgres:alpine
    container_name: eventhub-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres:
